const state={category:'all',entity:'all',tag:null,query:''};
let taxonomy={};let stories=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function setQuery(next){Object.assign(state,next);const q=new URLSearchParams();if(state.category!=='all')q.set('category',state.category);if(state.entity!=='all')q.set('entity',state.entity);if(state.tag)q.set('tag',state.tag);history.replaceState(null,'',q.toString()?`?${q}`:location.pathname);render()}
function matches(story){const q=state.query.trim().toLowerCase();const searchable=[story.title,story.summary,...(story.categories||[]),...(story.entities||[]),...(story.tags||[])].join(' ').toLowerCase();return(state.category==='all'||story.categories?.includes(state.category))&&(state.entity==='all'||story.entities?.includes(state.entity))&&(!state.tag||story.tags?.includes(state.tag))&&(!q||searchable.includes(q))}
function chip(label,value,kind){const b=document.createElement('button');b.className='nav-chip';b.textContent=label;b.dataset.value=value;b.onclick=()=>setQuery({[kind]:value,tag:null});if(state[kind]===value)b.classList.add('active');return b}
function renderNav(){const p=$('#primaryNav'),e=$('#entityNav');p.innerHTML='';e.innerHTML='';p.append(chip('전체','all','category'));(taxonomy.categories||[]).forEach(x=>p.append(chip(x.label,x.id,'category')));e.append(chip('모든 브랜드','all','entity'));(taxonomy.entities||[]).forEach(x=>e.append(chip(x.label,x.id,'entity')))}
function labelFor(group,id){return taxonomy[group]?.find(x=>x.id===id)?.label||id}
function openStory(story){location.href=`./article.html?id=${encodeURIComponent(story.id)}`}
function storyCard(story,compact=false){const node=$('#storyTemplate').content.firstElementChild.cloneNode(true);if(compact)node.classList.add('compact');node.querySelector('.story-meta').innerHTML=`<span class="badge">${esc(labelFor('categories',(story.categories||[])[0]||'news'))}</span>${(story.entities||[]).slice(0,2).map(x=>`<span>${esc(labelFor('entities',x))}</span>`).join('')}<span>· ${esc(story.publishedAt||'')}</span>`;node.querySelector('h3').textContent=story.title;node.querySelector('.story-summary').textContent=story.summary||'';node.querySelector('.story-footer').innerHTML=(story.tags||[]).slice(0,4).map(t=>`<span class="badge">#${esc(t)}</span>`).join('');node.onclick=()=>openStory(story);return node}
function renderFilters(){const box=$('#activeFilters');box.innerHTML='';if(state.category!=='all')box.innerHTML+=`<span class="filter-pill">${esc(labelFor('categories',state.category))}</span>`;if(state.entity!=='all')box.innerHTML+=`<span class="filter-pill">${esc(labelFor('entities',state.entity))}</span>`;if(state.tag)box.innerHTML+=`<span class="filter-pill">#${esc(state.tag)}</span>`}
function renderDaily(){const root=$('#dailyReport');root.innerHTML='';const daily=stories.find(x=>x.type==='daily-brief')||stories[0];if(!daily){root.innerHTML='<div class="empty">아직 데일리 리포트가 없습니다.</div>';return}const article=document.createElement('article');article.className='daily-card';article.innerHTML=`<div><div class="story-meta"><span class="badge">Daily Brief</span><span>${esc(daily.publishedAt||'')}</span></div><h3>${esc(daily.title)}</h3><p>${esc(daily.summary||'')}</p></div><div class="daily-topics">${(daily.tags||[]).slice(0,6).map(t=>`<span class="badge">#${esc(t)}</span>`).join('')}</div>`;article.onclick=()=>openStory(daily);root.append(article)}
function hubItems(hub){return stories.filter(s=>hub.kind==='entity'?s.entities?.includes(hub.id):s.categories?.includes(hub.id)).filter(s=>s.type!=='daily-brief').slice(0,4)}
function renderHubs(){const root=$('#homeHubs');root.innerHTML='';(taxonomy.homeHubs||[]).forEach(hub=>{const items=hubItems(hub);const section=document.createElement('section');section.className='hub-section';const action=hub.kind==='entity'?`setQuery({entity:'${hub.id}',category:'all',tag:null})`:`setQuery({category:'${hub.id}',entity:'all',tag:null})`;section.innerHTML=`<div class="section-head"><div><p class="eyebrow">Hub</p><h2>${esc(hub.label)}</h2></div><button class="text-link" type="button" onclick="${action}">전체보기 →</button></div><div class="hub-grid"></div>`;const grid=section.querySelector('.hub-grid');if(items.length)items.forEach(x=>grid.append(storyCard(x,true)));else grid.innerHTML='<div class="empty">아직 이 허브에 축적된 콘텐츠가 없습니다.</div>';root.append(section)})}
function render(){renderNav();renderFilters();renderDaily();renderHubs();const filtered=stories.filter(matches);$('#resultCount').textContent=`${filtered.length}건`;$('#latestTitle').textContent=state.category==='all'&&state.entity==='all'&&!state.tag&&!state.query?'최신 콘텐츠':`${state.entity!=='all'?labelFor('entities',state.entity):state.category!=='all'?labelFor('categories',state.category):state.tag?`#${state.tag}`:'검색'} 최신`;const list=$('#latestList');list.innerHTML='';filtered.forEach(x=>list.append(storyCard(x,false)));if(!filtered.length)list.innerHTML='<div class="empty">조건에 맞는 콘텐츠가 없습니다.</div>';renderTrending(filtered)}
function renderTrending(source){const counts=new Map();source.forEach(s=>(s.tags||[]).forEach(t=>counts.set(t,(counts.get(t)||0)+1)));const root=$('#trendingTags');root.innerHTML='';[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,12).forEach(([t])=>{const b=document.createElement('button');b.className='tag-button';b.textContent=`#${t}`;b.onclick=()=>setQuery({tag:t});root.append(b)})}
async function init(){const params=new URLSearchParams(location.search);state.category=params.get('category')||'all';state.entity=params.get('entity')||'all';state.tag=params.get('tag');[taxonomy,{items:stories}]=await Promise.all([fetch('./data/taxonomy.json').then(r=>r.json()),fetch('./data/index.json').then(r=>r.json())]);stories.sort((a,b)=>String(b.publishedAt||'').localeCompare(String(a.publishedAt||'')));render();$('#searchToggle').onclick=()=>{$('#searchPanel').classList.toggle('hidden');if(!$('#searchPanel').classList.contains('hidden'))$('#searchInput').focus()};$('#searchInput').oninput=e=>{state.query=e.target.value;render()}}
init().catch(err=>{console.error(err);$('#latestList').innerHTML='<div class="empty">콘텐츠 데이터를 불러오지 못했습니다.</div>'});
